# Generated by Django 5.2 on 2025-05-01 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('entity', models.CharField(max_length=100, verbose_name='Сущность')),
                ('obj_id', models.CharField(max_length=100, verbose_name='ID объекта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('changes', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
