# Generated by Django 5.2 on 2025-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_inn',
            field=models.CharField(default='123456789010', max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
