# Generated by Django 5.2 on 2025-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction_receiver_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий к операции.'),
        ),
    ]
